require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ExpanseManager' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

  pod 'react-native-html-to-pdf', :path => '../node_modules/react-native-html-to-pdf'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  pod 'RNCPicker', :path => '../node_modules/@react-native-picker/picker'

  pod 'RNFileViewer', :path => '../node_modules/react-native-file-viewer'

  target 'ExpanseManagerTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ExpanseManager-tvOS' do
  # Pods for ExpanseManager-tvOS

  target 'ExpanseManager-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
